spring.application.name=order-service
server.port=8083

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/order_service_db
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
product.service.base-url=http://localhost:8080/

# Logging Configuration
logging.level.root=WARN
logging.level.org.furmani.orderservice=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n

